name: ssh-cipher

on:
  pull_request:
    paths:
      - ".github/workflows/ssh-cipher.yml"
      - "ssh-cipher/**"
      - "ssh-encoding/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: ssh-cipher

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  # Disabled until we get rid of [patch.crates-io] in the workspace
  #minimal-versions:
  #  uses: RustCrypto/actions/.github/workflows/minimal-versions.yml@master
  #  with:
  #    stable-cmd: cargo test --all-features --release
  #    working-directory: ${{ github.workflow }}

  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.81.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - uses: RustCrypto/actions/cargo-hack-install@master
      - run: cargo hack build --target ${{ matrix.target }} --feature-powerset --exclude-features default,std

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.81.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - uses: RustCrypto/actions/cargo-hack-install@master
      - run: cargo hack test --feature-powerset
